### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [adampaulsackfield/beer-project#16]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages): DONE
2. A public GitHub repository for your codebase: DONE
3. Using Punk API: DONE
4. Tests where possible RTL: DONE

### Plan

- Start: DONE
  - Matching component tree & passing props?
- Stage 1: DONE
  - Search functionality?
- Stage 2: DONE
  - Filters x 3?
- Stage 3: DONE
  - Styled?

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/03-react/punk-api-marking.md)

| Category          | Score     |
| ----------------- | --------- |
| Functionality     | 55 / 55   |
| Testing           | 10 / 10   |
| Project Structure | 10 / 10   |
| React Use         | 20 / 20   |
| Design            | 15 / 15   |
| Total Score       | 110 / 110 |

## Positive

- Again I have got to give you kudos for your tenacity not only have you extended the brief you have written it in a superset of JS!
- You are the first person to hand this brief in as a Typescript project, it is Awesome!

  - Doing this will set you up for Java nicely!

- You have multiple functions and bits of data being passed across your application to the components that need them using props!

- You are utilizing the power of query params to do your filtering for you!
  - I like that you have broken it out into a service.
  
- I think you will enjoy having a look at this [Testing repo](https://github.com/nology-tech/thrones-reindeer) that we did as a recap during the Xmas break. I went a bit other board or just had some fun. A couple of people had asked for more complex tests so that's what they got :).

  - There are some examples of how you can test your service & the components that use it.

- I feel confident with your understanding of props, useState, useEffect and funcs as props.

- Awesome, good going! it is a big project and I can't wait to see what you build next.

## Constructive

- I have managed to remove the warning squiggly lines in your `useEffect`. notes are below.

```js
// BeersContainer.tsx
// PASS IN BOTH BITS OF STATE YOU RELY ON & JUST MAKE SURE YOU USE THEM
// - A COUPLE OF PLACES YOU WERE USING THE STATE CACHE & FORM DATA
// - MAKE SURE YOU ARE REFERRING TO THE PARAMETERS NOT THE STATE
const handleRequest = async (requestCache, formObj) => {
  const query = { ...formObj };

  const queryString = JSON.stringify(query);

  const isCached = requestCache.has(queryString);

  if (isCached) {
    setBeers(requestCache.get(queryString));
    return console.log("Cached Version");
  }

  try {
    const response = await getBeers(formObj);
    setCache(requestCache.set(queryString, response));
    setBeers(response);
    return console.log("API Version");
  } catch (error) {
    return console.log("ERROR");
  }
};

useEffect(() => {
  // PASS THE STATE IN & UPDATE THE DEPENDENCY ARRAY
  handleRequest(cache, formData);
}, [cache, formData]);
```

- I like the effect you have achieved with your sidebar it does cause a couple of styling problems though.

  - On different screen sizes you get different results e.g. on a large screen some are cut off and on a smaller screen, you do not use the whole space.

  - I think I have fixed it notes are below.

  ```scss
  // _base.scss
  .container {
    // max-width: 1200px; DELETE THIS
    // CONSIDERING THE PAGE IS SHIFTED 250PX TO THE LEFT + ADD THAT ON
    width: calc(100vw + 250px);
    margin: 0 auto;
  }

  @media screen and (min-width: 1200px) {
    .container {
      // WHEN IT IS NOT SHIFTED 250px TO THE LEFT SET IT BACK
      width: unset;
    }
  }
  ```

  ```scss
  // BeersContainer.scss
  .beers {
    // width: 100vw; DELETE THIS
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    color: black;
    padding: 0 1rem;
  }

  @media screen and (min-width: 800px) {
    .beers {
      flex-direction: row;
      flex-wrap: wrap;
      // PLAY AROUND WITH HOW YOU WANT IT TO LOOK
      justify-content: space-between;
    }
  }
  ```

- React is not opinionated which means you can write it in multiple ways, from experience and personally I would try and keep the functions that update the state where that state is defined. e.g. use it in a function in `<LayoutContainer/>` and pass that function to the component that needs it.

  - At the moment with a couple of your components you give them the function to update it and then they do it in the component.
  - This means that the component isn't reusable anymore to the extent it is tied to that update state function.
    - If you instead define the function where the state is and pass it using props it isn't coupled/tied to it.
    - Making it more reusable.
  - Let's take an example, components have been simplified.

  ```tsx
  // LayoutContainer.tsx
  const LayoutContainer: React.FC = (): ReactElement => {
    const [formData, setFormData] = useState<FormInterface>(initialState);

    // MOVE FUNCTION FROM FORM & PASS IT DOWN
    const handleChange = (e): void => {
      setFormData({ ...formData, [e.target.name]: !formData[e.target.name] });
    };

    return (
      <Navbar
        // PASS THE SEARCH TERM
        searchTerm={formData.searchTerm}
        // PASS THE FUNCTION RATHER THAN THE FUNCTION TO UPDATE THE STATE
        handleChange={handleChange}
        basket={basket}
        showBasket={showBasket}
        toggleBasket={setShowBasket}
      />
    );
  };
  ```

  ```tsx
  // searchTerm, handleChange WOULD HAVE BEEN PASS THROUGH MULTIPLE COMPONENTS
  const Form: React.FC<FormProps> = ({ searchTerm, handleChange }): ReactElement => {
    // YOU WOULD MOVE THIS FUNCTION UP AS WELL
    // const handleInput = (e): void => {
    //   setFormData({ ...formData, searchTerm: e.target.value.toLowerCase() });
    // };

    return (
      <form className="form">
        <h2 className="form__header">Filter</h2>

        <input
          className="form__input"
          type="text"
          name="searchTerm"
          id="search"
          placeholder="Search term..."
          value={searchTerm}
          // onChange={handleInput} WILL HAVE TO UPDATE THIS
        />

        <label className="form__label" htmlFor="highAbv">
          <p className="form__label--text">High ABV &gt; 6% </p>
          <CiPercent className="form__label--icon" />
          // USE THE FUNCTION GIVEN AS PROPS
          <input className="form__checkbox" type="checkbox" name="highAbv" id="highAbv" onChange={handleChange} />
        </label>
      </form>
    );
  };
  ```

  - As I said there isn't one way of writing React, above is just an example so if you don't agree that's cool as it still works and isn't being reused so doesn't need the refactoring.
  - Any questions give me a shout.

---
